/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ChecklistSection: typeof import('./src/components/ChecklistSection.vue')['default']
    EmployeePicker: typeof import('./src/components/EmployeePicker.vue')['default']
    KanbanColumn: typeof import('./src/components/KanbanColumn.vue')['default']
    NewTaskDialog: typeof import('./src/components/NewTaskDialog.vue')['default']
    ProgressRing: typeof import('./src/components/ProgressRing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskDetailModal: typeof import('./src/components/TaskDetailModal.vue')['default']
    TimesheetSection: typeof import('./src/components/TimesheetSection.vue')['default']
    Toasts: typeof import('./src/components/Toasts.vue')['default']
  }
}
