"""Bootstrap for the standalone SPA at /agile.

The matching agile.html is generated by the frontend build (frappe-ui's vite
plugin copies the built index.html here and injects a Jinja block that turns
every key of `context.boot` into a `window` global — including csrf_token,
which frappe-ui's request layer sends as X-Frappe-CSRF-Token).
"""

import frappe
from frappe import _

no_cache = 1


def get_context(context):
    if frappe.session.user == "Guest":
        frappe.local.flags.redirect_location = "/login?redirect-to=/agile"
        raise frappe.Redirect

    from agile_projects.api import check_app_permission

    if not check_app_permission():
        frappe.throw(
            _("You do not have permission to access Agile Projects"),
            frappe.PermissionError,
        )

    frappe.db.commit()
    context.boot = get_boot()
    return context


@frappe.whitelist(methods=["GET", "POST"], allow_guest=True)
def get_context_for_dev():
    if not frappe.conf.developer_mode:
        frappe.throw(_("This method is only meant for developer mode"))
    return get_boot()


def get_boot():
    return frappe._dict(
        {
            "frappe_version": frappe.__version__,
            "default_route": "/agile",
            "site_name": frappe.local.site,
            "read_only_mode": frappe.flags.read_only,
            "csrf_token": frappe.sessions.get_csrf_token(),
            "socketio_port": frappe.conf.socketio_port,
            "sysdefaults": frappe.defaults.get_defaults(),
        }
    )
